import type { Metadata } from "next";
import "./globals.css";

import { Be_Vietnam_Pro } from "next/font/google";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import BackToTop from "@/components/BackToTop";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["vietnamese"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={beVietnamPro.className}>
        <Header />
        {children}
        <BackToTop />
        <Footer />
      </body>
    </html>
  );
}
